name: default
fullyQualifiedName: mysql_sample.default
dataProducts: []
tags: []
owners: []
service:
  id: 6191499b-95f1-4a0e-aa26-93f08af06a0d
  type: databaseService
  name: mysql_sample
  fullyQualifiedName: mysql_sample
  displayName: mysql_sample
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: b250a6b7-efc0-4762-8e0f-a76dfc054338
    type: databaseSchema
    name: posts_db
    fullyQualifiedName: mysql_sample.default.posts_db
    displayName: posts_db
    deleted: false
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: certification
      oldValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Manual\",\"state\":\"Confirmed\"},\"appliedDate\":1770382180891,\"\
        expiryDate\":1772974180891}"
      newValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Automated\",\"state\":\"Confirmed\"},\"appliedDate\":1770382184927,\"\
        expiryDate\":1772974184927}"
  fieldsDeleted: []
  previousVersion: 0.4
  changeSummary: {}
default: false
sourceUrl: https://localhost:3306/posts_db
domains: []
certification:
  tagLabel:
    tagFQN: Certification.Silver
    name: Silver
    description: Silver certified Data Asset.
    style:
      color: "#ADADAD"
      iconURL: SilverCertification.svg
    source: Classification
    labelType: Manual
    state: Confirmed
  appliedDate: 1770382184928
  expiryDate: 1772974184928
entityStatus: Unprocessed
